services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ../..:/home/user
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DB=postgis
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  db:
